### ISSUE TITLE
Feature request: add buttons to filter charts by release channel

### ISSUE THREAD

**Issue by philipp-sumo** [ashughes1/bugzilla-socorro-lens#18]
I have an enhancement request for the extension: it would be quite helpful if there was a quick way to only show crashes for a specified channel (release, beta, aurora, nightly, esr) in the chart - especially in situations where you have to evaluate when a bug started to regress on a channel or to see if a fix works once a patch landed on a particular channel.

**Comment by ashughes1** [comment]
@philipp-sumo I have added this feature now. Try it out and let me know if it works.

@marco-c since you've been involved in this project I'd love to know what you think too.

Thanks

**Comment by philipp-sumo** [comment]
thanks a bunch, it works great and will come in handy in many circumstances. 
also the smooth transitions look very nice... :))

**Comment by marco-c** [comment]
I think it's a very useful addition!
