### ISSUE TITLE
Impending breakage due to CSP

### ISSUE THREAD

**Issue by dylanwh** [ashughes1/bugzilla-socorro-lens#19]
I have a strong suspicion that [Bug 1286290](https://bugzilla.mozilla.org/show_bug.cgi?id=1286290) is going to break this extension.

Probably should see about doing issue #2 if enough people are using this.

**Comment by ashughes1** [comment]
The options here are to get someone to do the work in bmo to resolve issue #2 or to fix the add-on so it works given the CSP changes. Unfortunately both are beyond my ability to fix. I know there are senior levels of the organization who are using this add-on to assist in triage so I suggest integrating this with Bugzilla as a plugin might be the way to go and that you might consider this to block bug 1286290.

I'm happy to assist any way that I can but my knowledge about CSP and Bugzilla plugins is next to zero so I'll need some mentorship.

**Comment by dylanwh** [comment]
We still want to land CSP like, next week ideally. So I've added an exception that will let this work. It was pretty simple: I added 'https://ashughes1.github.io/bugzilla-socorro-lens/chart.htm' to child-src. 

This is a temporary work around until we resolve issue #2 / [bug 1332016](https://bugzilla.mozilla.org/show_bug.cgi?id=1332016)
