### ISSUE TITLE
Investigate integrating chart with bugzilla.mozilla.org

### ISSUE THREAD

**Issue by ashughes1** [ashughes1/bugzilla-socorro-lens#2]
Being able to load charts without needing to install an add-on would improve visibility and usefulness to more people.

**Comment by dylanwh** [comment]
The main requirements (off the top of my head) are that we cannot load JS or CSS from a CDN. I can probably ask a certain volunteer to do some of the work.

**Comment by dylanwh** [comment]
Okay, so the plugin just parses the crash signature,
and then makes an iframe pointing to https://github.com/ashughes1/bugzilla-socorro-lens/blob/master/chart.html

*ideally* we would want to make that not an iframe, but realistically we can serve chart.html from BMO. That part's not so bad.

The bad part is we don't allow loading JS/CSS from CDNs, so we'd need to bundle that too.

**Comment by dylanwh** [comment]
@sebastinsanty, up for a challenge?

**Comment by SebastinSanty** [comment]
Yup.

**Comment by ashughes1** [comment]
Thanks guys, I'm happy to help test and push any changes needed to this repo.

**Comment by dylanwh** [comment]
@ashughes1 What's your bugmail? I'm going to file a bug for this in the morning (probably with @SebastinSanty as the asignee) and I'll make sure you're CC'd on it.

we *could* write a CSP that allowed the iframe to load the resource from this github, but security minded folks will not appreciate that.  Rather we'd put the content of chart.html into (some path) on bugzilla, bundle the JS and CSS deps, and (finally) make the template change so that the firefox script doesn't have to add any iframe.

I guess we'll add some hidden DOM attribute and this extension can check for that?

**Comment by ashughes1** [comment]
Yeah, I think we should do whatever is going to cause the least amount of friction and will be more easily maintainable long-term. You can find me in Bugzilla using the shorthand :ashughes.

**Comment by ashughes1** [comment]
@dylanwh I'm going to be working on this as part of my Q4 work. I've looked over the [gist](https://gist.github.com/dylanwh/3a47b1a189dfedf2f86454ac684ac20a) you provided to get me started and I've managed to get a local BZ instance running under Vagrant. I've also looked at Sebastin's PR and have a good sense of what I'm trying to do from that, however I'm not quite sure what the best approach is.

It seems like the current approach would be to just integrate the JS/HTML/CSS as part of the native product so that everyone gets it. However another approach would be to just write a BZ extension (I see quite a few in the Extensions folder). What is the preferred approach?

Once we've settled on an approach, my next question is how do we get the HTML/JS/CSS to load when required? Right now I do the detection through my WebExtension's content.js file. I'm assuming I need to add similar logic to show_bugs.cgi or some other file loaded from show_bugs.cgi. What do you advise?

**Comment by dylanwh** [comment]
The Bug Modal UI doesn't really support extensions -- because it is an Extension, so effectively this will go into the BugModal extension: extensions/BugModal/template/en/default/bug_modal is the place to start looking. If you tell me the DOM nodes you're using, I'll tell you the files.

The static assets can go under extensions/BugModal/web/, which will resolve to https://bugzilla.mozilla.org/extensions/BugModal/web/whatever

**Comment by ashughes1** [comment]
@dylanwh okay so given the Bug Modal UI the best way is to just do this natively (without extensions). As a starting point I need to modify the Crash Signature field to inject a chart. Where can I find the code for the Crash Signature field?

**Comment by ashughes1** [comment]
@dylanwh I've made significant progress and now have the chart loading and operating correctly. The only functionality that is missing is the zoom button.

Using the addon, the zoom button sits outside and to the right of the iframe (it's just an image with an onclick event handler). When clicked the iframe is scaled up and the zoom button image changes to the shrink image. When clicked again the iframe scales back down and the zoom button image source changes back to the enlarge image. The code for that exists in [content.js#17](https://github.com/ashughes1/bugzilla-socorro-lens/blob/master/addon/content.js#L17) from the add-on. 

I've not figured a way to do this with Perl inside the template file and if I try to run JS from the template file I get a CSP error. Do you have any idea how I might move forward with this?

Source:
[bmo-mg-v1.patch.txt](https://github.com/ashughes1/bugzilla-socorro-lens/files/1377219/bmo-mg-v1.patch.txt)

**Comment by ashughes1** [comment]
@dylanwh you can disregard my previous comments. I've got everything working in parity with the add-on and have now uploaded a patch for review to https://bugzil.la/1332016. Let's continue the conversation in that bug report.

**Comment by dylanwh** [comment]
Roger that! I'm taking a look now

**Comment by ashughes1** [comment]
Status update: I have submitted a pull request to https://github.com/mozilla-bteam/bmo/pull/263 for review and testing.

**Comment by ashughes1** [comment]
This should be going live tomorrow (Tuesday October 31, 2017). As such I am shutting down further development of the add-on, instead focusing on fixing issues and implementing new features with the integrated product over at https://github.com/ashughes1/bmo-bsl.

Thank you.
