### ISSUE TITLE
Addon stopped working on nightly

### ISSUE THREAD

**Issue by philipp-sumo** [ashughes1/bugzilla-socorro-lens#20]
since a couple of days the addon is broken on nightly and the graphs for crash signatures are no longer displayed in bugzilla.

this apparently started with https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=9bd131795d81977c1d21c9c4aff06b3f4c69956e&tochange=895164016ae91086fe04e1f5cafbaa3e46f3805d & https://bugzilla.mozilla.org/show_bug.cgi?id=1317697

**Comment by ashughes1** [comment]
Thanks, I noticed this too. I'll look in to how I can fix this.

**Comment by andymckay** [comment]
I think its because you are making an assumption that the content script is loaded once the DOM has been loaded. You can guarantee it is by using the onload event handler, or specify in the content script, for example:

https://gist.github.com/andymckay/c8bb8c072daa8f1945d81d24d4473d66

**Comment by ashughes1** [comment]
@andymckay Thank you very much! I test the manifest change and it works. I'll push this change shortly.

**Comment by ashughes1** [comment]
Updated .xpi has been submitted to AMO for review.
