### ISSUE TITLE
Issues with graphing

### ISSUE THREAD

**Issue by philipp-sumo** [ashughes1/bugzilla-socorro-lens#24]
recently, some of the signature graphs started to look a bit funny - example:
![grafik](https://user-images.githubusercontent.com/1524147/30173599-7f0ea25a-93f8-11e7-97b7-827d6b41d913.png)
(that one's from https://bugzilla.mozilla.org/show_bug.cgi?id=1396268)

**Comment by ashughes1** [comment]
This looks resolved on my end now with the above commit.

@philipp-sumo please confirm and close if fixed.

**Comment by philipp-sumo** [comment]
yeah, looks fine from here too. thank you!

**Comment by ashughes1** [comment]
Thanks for checking and for reporting. As it turns out the bug here resulted in numbers being misreported as one less than actual.
