### ISSUE TITLE
Splicing API calls fails if one of the calls returns no data

### ISSUE THREAD

**Issue by ashughes1** [ashughes1/bugzilla-socorro-lens#25]
From [comment #332824473](https://github.com/ashughes1/bugzilla-socorro-lens/issues/11#issuecomment-332824473) in issue #11:

> Hey Anthony, I've noticed the addon is not working again in some bugs with long signatures, e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1158189 or https://bugzilla.mozilla.org/show_bug.cgi?id=1267692.

In this case the amount and length of signatures is so long that I splice data retrieval across multiple API calls, otherwise we'd fail due to an out of bounds URL length. There is a bug in my code not handling the case where we return no data from one or more of these calls, resulting in the chart draw call never occurring. I have a fix for this which I will add momentarily.

**Comment by ashughes1** [comment]
@marco-c please verify if this is fixed on your end.

**Comment by marco-c** [comment]
Thanks, it's working now!

**Comment by ashughes1** [comment]
Thanks for testing and reporting.
