### ISSUE TITLE
Displayed crash volume is only going back 6 months

### ISSUE THREAD

**Issue by philipp-sumo** [ashughes1/bugzilla-socorro-lens#7]
Maybe you could adjust the range of the chart accordingly, so that it doesn't show a flat line for the first 6 months in every crash bug.

**Comment by ashughes1** [comment]
Yeah, it seems like I'm only getting 6 months of crash data even though the API states 365 days is supported. I'll get this fixed soon. Thanks.

**Comment by ashughes1** [comment]
This should now be fixed.

**Comment by philipp-sumo** [comment]
thanks :-)
