### ISSUE TITLE
Make the chart bigger

### ISSUE THREAD

**Issue by marco-c** [ashughes1/bugzilla-socorro-lens#8]
It's 300x150 now, it'd be more readable if it was bigger.

**Comment by ashughes1** [comment]
Hi @marco-c, thanks for the contribution.

I was looking in to this today and 500x300 seems a bit too big for me. To me 300x150 is the ideal size as it fits other elements on the page. However I recognize that 300x150 might be too small for others. This got me thinking, what if there was a way to allow the user to resize the viewport, perhaps by way of a pref. Would this satisfy your requirements?

**Comment by ashughes1** [comment]
@marco-c this should be fixed with the latest merge (noted above) and version 0.5.3 of the addon (pending AMO review). I've implemented it a bit differently but it should work more or less. It's probably not perfect so please test it out and let me know what you think.

**Comment by marco-c** [comment]
Looks good to me, thanks!
