### ISSUE TITLE
Last two days in the x axis is 0 for all signatures

### ISSUE THREAD

**Issue by marco-c** [ashughes1/bugzilla-socorro-lens#9]
For example, in https://bugzilla.mozilla.org/show_bug.cgi?id=1267970, I see 0 crashes on Sep 6 and Sep 7, but there are respectively 114 and 36 (even if you only consider just one of the signatures from the bug, atiumdag.dll | atiu9pag.dll | TrimNotificationCallback: https://crash-stats.mozilla.com/signature/?signature=atiumdag.dll%20%7C%20atiu9pag.dll%20%7C%20TrimNotificationCallback#graphs).

**Comment by marco-c** [comment]
I'm not sure about the second to last day, but the last day is failing because the query contains a date that is in the future.
E.g. https://crash-stats.mozilla.com/search/?signature=~arena_dalloc_small%20%7C%20je_free%20%7C%20nsTArray_base%3CT%3E%3A%3AShiftData%3CT%3E%20%7C%20nsTArray_Impl%3CT%3E%3A%3ADestructRange%20%7C%20mozilla%3A%3APaintedLayerData%3A%3A~PaintedLayerData&date=%3E%3D2016-09-09&date=%3C2016-09-10&page=1&_sort=-date&_facets=signature&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform

Today is 2016-09-09, so you can't use 2016-09-10 (Socorro fails with 'date can't be in the future').'

**Comment by marco-c** [comment]
The other issue is that the graph is starting from one day after start_date, so ends with one day after end_date.

**Comment by ashughes1** [comment]
This is now fixed by commit dc6cf7a.
